version: '3'

services:
        web:
                container_name: django_app
                restart: always
                build: 
                        context: .
                        dokerfile: Dockerfile
                        # ./django_app
                ports: 
                        - "8000:8000"
                command: gunicorn <django_project>.wsgi:application --bind 0.0.0.0:8000
                # settings.py 환경분리 되어있어 settings 를 지정해야하는 경우 다음과 같이 추가 입력
                # [--env DJANGO_SETTINGS_MODULE='<django_project>.settings.production']
                
                volumes:
                        - .:/code
                expose:
                        - "8000"

        nginx :
                image: nginx:latest
                container_name: nginx
                restart: always
                build: ./nginx
                ports:
                        - "80:80"
                depends_on:
                        - web
                volumes:
                        - .:/code
                        - ./config/nginx:/etc/nginx.conf.d



